### PR TITLE
Update (localization/en.lua) Removed duplicate query

### PR DESCRIPTION
**Pull request by NikartikTheBear**
Removed duplicated query, already present in weaponshop.sql

### CODE REVIEW

**Comment by NikartikTheBear** [comment]
> Hi! @NikartikTheBear Thank you for help but i think should not be deleted because then if someone tries to use it, it will not be correct.

wouldn't be more confusing by leaving it since it would trigger an sql duplicate error if importing in the database? May be the best solution would be to put everything into a single sql file?

**Comment by Gellipapa** [comment]
> > Hi! @NikartikTheBear Thank you for help but i think should not be deleted because then if someone tries to use it, it will not be correct.
> 
> wouldn't be more confusing by leaving it since it would trigger an sql duplicate error if importing in the database? May be the best solution would be to put everything into a single sql file?

Yes or rewrite query ignore if table exist.

**Comment by Gellipapa** [comment]
Correct query: 
```
INSERT IGNORE INTO `licenses` (`type`, `label`) VALUES
	('weapon', "Weapons license")
;
```

**Comment by NikartikTheBear** [comment]
then i'll leave it up to you to decide if changing it or leaving it at that

**Comment by Gellipapa** [comment]
> then i'll leave it up to you to decide if changing it or leaving it at that

Okey, If you like you can write in it and then i can merge. What I wrote above should be add and committed.

**Comment by NikartikTheBear** [comment]
updated with your suggestion, thank you for the tip

**Comment by Gellipapa** [comment]
@NikartikTheBear Thank you i merged.

**Pull request merged**
